### ISSUE TITLE
msvcr100.dll required but not available

### ISSUE THREAD

**Issue by miweber67** [airspy/firmware#25]
airspy_spiflash.exe requires msvcr100.dll, which despite several hours of searching and installing I have not been able to locate. Please provide a link to the required installer or rebuild airspy_spiflash.exe with a more recent redistributable requirement?

**Comment by bvernoux** [comment]
This issue is not related to firmware as the firmware is what is flashed and embedded in AirSpyOne
So it is related to https://github.com/airspy/airspyone_host
For information this DLL msvcr100.dll is required by pthreadVC2.dll (x64) or pthreadVCE2.dll (x86) and is part of Microsoft Visual C++ 2010 Redistributable (or more) see https://answers.microsoft.com/en-us/windows/forum/all/msvcr100-dll/826a842c-7a2f-4ebc-bb21-4cee86b234b0

**Comment by miweber67** [comment]
Thanks for the reply! It turns out I needed the x86 version even though I have an x64 machine.
